# 🇨🇴 Colombia INS (Instituto Nacional de Salud) Data Access

This notebook demonstrates how to access public health surveillance data from **Colombia's National Health Institute (INS)**, including SIVIGILA (Public Health Surveillance System) data.

## Overview

The Colombian INS manages the SIVIGILA system for notifiable disease surveillance, covering:
- **Vector-borne diseases**: Dengue, Malaria, Chikungunya, Zika, Yellow fever
- **Respiratory diseases**: COVID-19, Influenza, IRA
- **Water and food-borne diseases**: Hepatitis, EDA
- **Sexually transmitted infections**: VIH/SIDA, Syphilis
- **Tuberculosis and Leprosy**
- **Public health events of interest**: Suicide attempts, violence, traffic accidents

**Website:** https://www.ins.gov.co/

**Open Data Portal:** https://www.datos.gov.co

## 📦 Setup

In [1]:
import sys

import matplotlib.pyplot as plt
import pandas as pd

from epidatasets.sources.colombia_ins import ColombiaINSAccessor

# Initialize accessor
ins = ColombiaINSAccessor()

print("✅ Colombia INS Accessor initialized successfully!")

✅ Colombia INS Accessor initialized successfully!

## 🗺️ Exploring Colombian Geography

Colombia is divided into 33 departments (departamentos) organized into 5 geographical regions:

In [2]:
# List all departments
departments = ins.list_departments()
print(f"Total departments: {len(departments)}")
print("\nFirst 10 departments:")
departments.head(10)

Total departments: 33

First 10 departments:

  department_code department_name
0              05       Antioquia
1              08       Atlántico
2              11    Bogotá, D.C.
3              13         Bolívar
4              15          Boyacá
5              17          Caldas
6              18         Caquetá
7              19           Cauca
8              20           Cesar
9              23         Córdoba

In [3]:
# View departments by region
regions = {
    "Andina": ins.get_departments_by_region('Andina'),
    "Caribe": ins.get_departments_by_region('Caribe'),
    "Pacífica": ins.get_departments_by_region('Pacífica'),
    "Orinoquía": ins.get_departments_by_region('Orinoquía'),
    "Amazonía": ins.get_departments_by_region('Amazonía'),
}

for region, depts in regions.items():
    dept_names = [ins.DEPARTMENTS[d] for d in depts]
    print(f"\n📍 {region} ({len(depts)} departments):")
    print("  " + ", ".join(dept_names[:5]) + ("..." if len(dept_names) > 5 else ""))

📍 Andina (10 departments):
  Antioquia, Bogotá, D.C., Boyacá, Caldas, Cundinamarca...

📍 Caribe (8 departments):
  Atlántico, Bolívar, Cesar, Córdoba, La Guajira...

📍 Pacífica (4 departments):
  Cauca, Chocó, Nariño, Valle del Cauca

📍 Orinoquía (4 departments):
  Meta, Arauca, Casanare, Vichada

📍 Amazonía (6 departments):
  Caquetá, Putumayo, Amazonas, Guainía, Guaviare...

## 🦠 Notifiable Diseases (SIVIGILA)

SIVIGILA tracks 33 notifiable diseases organized into event groups:

In [4]:
# List all diseases
diseases = ins.list_diseases()
print(f"Total notifiable diseases: {len(diseases)}\n")
diseases.head(10)

Total notifiable diseases: 33

  disease_code                 disease_name
0          100                       DENGUE
1          110                 DENGUE GRAVE
2          111  DENGUE CON SIGNOS DE ALARMA
3          120                      MALARIA
4          130                  CHIKUNGUNYA
5          140                         ZIKA
6          150              FIEBRE AMARILLA
7          160                LEISHMANIASIS
8          170                LEPTOSPIROSIS
9          180                 RABIA HUMANA

In [5]:
# View diseases by event group
event_groups = ins.list_event_groups()

for group in event_groups['event_group'].unique():
    group_diseases = event_groups[event_groups['event_group'] == group]
    print(f"\n📋 {group} ({len(group_diseases)} diseases):")
    for _, row in group_diseases.head(5).iterrows():
        print(f"  - {row['disease_code']}: {row['disease_name']}")
    if len(group_diseases) > 5:
        print(f"  ... and {len(group_diseases) - 5} more")

📋 ENFERMEDADES TRANSMITIDAS POR VECTORES (9 diseases):
  - 100: DENGUE
  - 110: DENGUE GRAVE
  - 111: DENGUE CON SIGNOS DE ALARMA
  - 120: MALARIA
  - 130: CHIKUNGUNYA
  ... and 4 more

📋 ENFERMEDADES DE TRANSMISIÓN RESPIRATORIA (6 diseases):
  - 310: INFLUENZA
  - 320: IRA (Infecciones Respiratorias Agudas)
  - 350: SARAMPIÓN
  - 360: RUBÉOLA
  - 390: PERTUSSIS
  ... and 1 more

📋 ENFERMEDADES DE TRANSMISIÓN HÍDRICA Y ALIMENTARIA (5 diseases):
  - 240: HEPATITIS B
  - 250: HEPATITIS C
  - 330: EDA (Enfermedades Diarreicas Agudas)
  - 370: TÉTANOS NEONATAL
  - 380: TÉTANOS ACCIDENTAL

📋 TUBERCULOSIS Y LEPRA (1 diseases):
  - 190: TUBERCULOSIS

📋 VIH E ITS (3 diseases):
  - 210: SÍFILIS GESTACIONAL
  - 220: SÍFILIS CONGENITA
  - 230: VIH/SIDA

📋 RABIA (1 diseases):
  - 180: RABIA HUMANA

📋 EVENTOS DE INTERÉS EN SALUD PÚBLICA (4 diseases):
  - 260: INTENTO DE SUICIDIO
  - 270: VIOLENCIA INTERPERSONAL
  - 280: ACCIDENTE DE TRÁNSITO
  - 340: PARALISIS FLÁCIDA AGUDA

## 🦟 Dengue Surveillance

Dengue is a priority disease in Colombia with mandatory weekly reporting. Let's access dengue data:

In [6]:
# Get dengue data for recent years
# Note: Actual data requires integration with datos.gov.co API
dengue_data = ins.get_dengue_data(
    years=[2022, 2023],
    departments=['05', '76', '11']  # Antioquia, Valle del Cauca, Bogotá
)

print(f"Dengue data records: {len(dengue_data)}")
print("\nDengue types tracked:")
print(dengue_data[['disease_code', 'disease_name']].drop_duplicates())

INFO:epidatasets.sources.colombia_ins:Fetching dengue data for years [2022, 2023], departments ['05', '76', '11']
INFO:epidatasets.sources.colombia_ins:Fetching SIVIGILA data for 3 diseases, 3 departments
WARNING:epidatasets.sources.colombia_ins:SIVIGILA data requires integration with datos.gov.co API or manual extraction from INS weekly bulletins

Dengue data records: 18

Dengue types tracked:
   disease_code                 disease_name
0           100                       DENGUE
6           110                 DENGUE GRAVE
12          111  DENGUE CON SIGNOS DE ALARMA

In [7]:
# Dengue by department
print("\nDengue surveillance by department:")
dengue_by_dept = dengue_data.groupby('department_name').size().reset_index(name='records')
dengue_by_dept

Dengue surveillance by department:

   department_name  records
0        Antioquia        6
1     Bogotá, D.C.        6
2  Valle del Cauca        6

## 🦟 Malaria Surveillance

Malaria is endemic in several Colombian regions, particularly the Pacific coast and Amazon:

In [8]:
# Get malaria data for Amazon and Pacific regions
amazon_depts = ins.get_departments_by_region('Amazonía')
pacific_depts = ins.get_departments_by_region('Pacífica')

malaria_data = ins.get_malaria_data(
    years=[2022, 2023],
    departments=amazon_depts + pacific_depts
)

print(f"Malaria data records: {len(malaria_data)}")
print("\nMalaria types tracked:")
print(malaria_data[['disease_code', 'disease_name']].drop_duplicates())

INFO:epidatasets.sources.colombia_ins:Fetching malaria data for years [2022, 2023], departments ['18', '86', '91', '94', '95', '97', '19', '27', '52', '76']
INFO:epidatasets.sources.colombia_ins:Fetching SIVIGILA data for 2 diseases, 10 departments
WARNING:epidatasets.sources.colombia_ins:SIVIGILA data requires integration with datos.gov.co API or manual extraction from INS weekly bulletins

Malaria data records: 40

Malaria types tracked:
   disease_code        disease_name
0           120             MALARIA
20          290  MALARIA COMPLICADA

## 🦠 Arbovirus Surveillance (Dengue, Chikungunya, Zika, Yellow Fever)

Colombia conducts integrated surveillance for arboviruses due to similar transmission patterns:

In [9]:
# Get all arbovirus data
arbovirus_data = ins.get_arbovirus_data(
    years=[2023],
    departments=ins.get_departments_by_region('Caribe')
)

print(f"Arbovirus surveillance records: {len(arbovirus_data)}")
print("\nArboviruses tracked:")
arbovirus_summary = arbovirus_data[['disease_code', 'disease_name']].drop_duplicates()
arbovirus_summary

INFO:epidatasets.sources.colombia_ins:Fetching arbovirus data for years [2023], departments ['08', '13', '20', '23', '44', '47', '70', '88']
INFO:epidatasets.sources.colombia_ins:Fetching SIVIGILA data for 6 diseases, 8 departments
WARNING:epidatasets.sources.colombia_ins:SIVIGILA data requires integration with datos.gov.co API or manual extraction from INS weekly bulletins

Arbovirus surveillance records: 48

Arboviruses tracked:

   disease_code                 disease_name
0           100                       DENGUE
8           110                 DENGUE GRAVE
16          111  DENGUE CON SIGNOS DE ALARMA
24          130                  CHIKUNGUNYA
32          140                         ZIKA
40          150              FIEBRE AMARILLA

## 📊 Weekly Epidemiological Bulletins

The INS publishes weekly epidemiological bulletins (Boletines Epidemiológicos Semanales):

In [ ]:
# Get bulletins for a specific year
bulletins_2023 = ins.get_weekly_bulletins(year=2023)

In [11]:

print(f"Total bulletins in 2023: {len(bulletins_2023)}")
print("\nFirst 5 weeks:")
bulletins_2023.head()#[['year', 'week', 'data_source', 'note']]

Total bulletins in 2023: 53

First 5 weeks:

,year,week,filename,bulletin_url,created_date,status
0,2023,1,2023_Boletin_epidemiologico_semana_01.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,None,generated
1,2023,2,2023_Boletin_epidemiologico_semana_02.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,None,generated
2,2023,3,2023_Boletin_epidemiologico_semana_03.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,None,generated
3,2023,4,2023_Boletin_epidemiologico_semana_04.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,None,generated
4,2023,5,2023_Boletin_epidemiologico_semana_05.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,None,generated

In [12]:
# Get specific week bulletin
week_21 = ins.get_weekly_bulletins(year=2026, week=21)
print('Week 21 bulletin:')
week_21

INFO:epidatasets.sources.colombia_ins:Fetching weekly bulletins for year 2026, week 21
INFO:epidatasets.sources.colombia_ins:Querying INS SharePoint API for available bulletins
INFO:epidatasets.sources.colombia_ins:Found 22 available bulletins

Week 21 bulletin:

,year,week,filename,bulletin_url,created_date,status
0,2026,21,2026_Boletin_epidemiologico_semana_21.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-06-05T09:39:32Z,available

## 📈 Comparing Departments

Compare disease occurrence across departments over time:

## 📋 Summary by Department

Get summary statistics for a specific year:

In [13]:
# Get summary for vector-borne diseases
summary = ins.get_summary_by_department(
    year=2023,
    disease_group='ENFERMEDADES TRANSMITIDAS POR VECTORES'
)

print(f"Summary records: {len(summary)}")
print("\nFirst 10 departments:")
summary.head(10) if not summary.empty else "No data available"

INFO:epidatasets.sources.colombia_ins:Fetching SIVIGILA data for 9 diseases, all departments
WARNING:epidatasets.sources.colombia_ins:SIVIGILA data requires integration with datos.gov.co API or manual extraction from INS weekly bulletins

Summary records: 33

First 10 departments:

  department_code total_cases total_deaths  n_diseases department_name  year
0              05           0            0           9       Antioquia  2023
1              08           0            0           9       Atlántico  2023
2              11           0            0           9    Bogotá, D.C.  2023
3              13           0            0           9         Bolívar  2023
4              15           0            0           9          Boyacá  2023
5              17           0            0           9          Caldas  2023
6              18           0            0           9         Caquetá  2023
7              19           0            0           9           Cauca  2023
8              20           0            0           9           Cesar  2023
9              23           0            0           9         Córdoba  2023

## 📄 Downloading and Parsing Bulletin PDFs

The INS publishes weekly epidemiological bulletins as PDF documents on their SharePoint site.
Using the shared `PDFParser`, we can discover, download, cache, and extract structured data from these bulletins.

In [14]:
# List available bulletins from the INS SharePoint API
available = ins.list_available_bulletins(year=2026)
print(f'Found {len(available)} bulletins for 2026')
available.head(10)

INFO:epidatasets.sources.colombia_ins:Querying INS SharePoint API for available bulletins
INFO:epidatasets.sources.colombia_ins:Found 22 available bulletins

Found 22 bulletins for 2026

,year,week,filename,bulletin_url,created_date
0,2026,21,2026_Boletin_epidemiologico_semana_21.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-06-05T09:39:32Z
1,2026,20,2026_Boletin_epidemiologico_semana_20.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-05-29T11:04:31Z
2,2026,19,2026_Boletin_epidemiologico_semana_19.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-05-22T11:03:57Z
3,2026,18,2026_Boletin_epidemiologico_semana_18.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-05-15T12:58:14Z
4,2026,17,2026_Boletin_epidemiologico_semana_17.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-05-08T12:25:59Z
5,2026,16,2026_Boletin_epidemiologico_semana_16.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-05-01T02:54:41Z
6,2026,15,2026_Boletin_epidemiologico_semana_15.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-04-24T09:31:06Z
7,2026,14,2026_Boletin_epidemiologico_semana_14.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-04-17T09:36:08Z
8,2026,13,2026_Boletin_epidemiologico_semana_13.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-04-10T12:22:06Z
9,2026,12,2026_Boletin_epidemiologico_semana_12.pdf,https://www.ins.gov.co/buscador-eventos/Boleti...,2026-04-06T14:01:23Z

In [15]:
# Download the most recent bulletin
latest = available.iloc[0]
bulletin_url = latest['bulletin_url']
print(f'Downloading: {bulletin_url}')
pdf_path = ins.download_bulletin(bulletin_url)
print(f'Downloaded to: {pdf_path}')
print(f'File size: {pdf_path.stat().st_size / 1024 / 1024:.1f} MB')

INFO:epidatasets.utils.pdf:Using cached PDF: /home/fccoelho/.cache/epidatasets/colombia_ins/2026_Boletin_epidemiologico_semana_21.pdf

Downloading: https://www.ins.gov.co/buscador-eventos/BoletinEpidemiologico/2026_Boletin_epidemiologico_semana_21.pdf
Downloaded to: /home/fccoelho/.cache/epidatasets/colombia_ins/2026_Boletin_epidemiologico_semana_21.pdf
File size: 12.2 MB

In [17]:
# Extract metadata
result = ins.parse_bulletin_pdf(pdf_path, extract_text=True, extract_tables=True)
meta = result['metadata']
print('Document Metadata:')
print(f'  Title: {meta.title}')
print(f'  Author: {meta.author}')
print(f'  Creation Date: {meta.creation_date}')
print(f'  Pages: {meta.page_count}')
print(f'  Text length: {len(result["text"])} chars')
print(f'  Tables found: {result.get("table_count", 0)}')

INFO:epidatasets.utils.pdf:Extracted 36 table(s) from 2026_Boletin_epidemiologico_semana_21.pdf

Document Metadata:
  Title: None
  Author: None
  Creation Date: D:20260604221716-05'00'
  Pages: 50
  Text length: 167973 chars
  Tables found: 36

In [18]:
# Preview text from first pages
text = result['text']
print('--- First 500 characters ---')
print(text[:500])

--- First 500 characters ---
Evaluación del desempeño
de las entidades territoriales
en vigilancia en salud pública
La vigilancia en salud pública no se mide
únicamente por los resultados alcanzados,
sino por la capacidad de cada territorio para
aprender, mejorar y responder oportunamente a
los desafíos que afectan la salud de su población.
21
Semana
epidemiológica
24 al 30 de mayo de 2026
Año 21
Boletín Epidemiológico Semanal
Imagen generada con IA.

El Boletín Epidemiológico Semanal (BES) es una publicación de tipo

In [19]:
# Display extracted tables
tables = result['tables']
print(f'Found {len(tables)} table(s)')

for i, t in enumerate(tables[:6]):
    print(f'\nTable {i+1}: Page {t.page_number}, {len(t.data)} rows x {len(t.data.columns)} cols')
    if t.caption:
        print(f'  Caption: {t.caption}')
    display(t.data.head(3))

Found 36 table(s)

Table 1: Page 10, 7 rows x 4 cols

  Sección eventos última semana Evento Observado Esperado      p
0                                 Zika         3        1  <0,05
1       Fiebre tifoidea y paratifoidea         5        1   0.03
2                Mortalidad por dengue        10        3   0.00

Table 2: Page 10, 3 rows x 1 cols

  Sección eventos última semana Evento Violencia de género e intrafamiliar
0                      Sección eventos última semana
1                                             Evento
2                Violencia de género e intrafamiliar

Table 3: Page 13, 35 rows x 10 cols

,Entidad territorial residencia,Casos confirmados a SE 21 2026 DNT,IRA,EDA,Casos en estudio a SE 21 2026 DNT,IRA,EDA,Tasa a SE 21 2026 DNT,IRA,EDA
0,Colombia,18,49,22,23,70,19,"0,49","1,35","0,60"
1,Antioquia,2,4,0,2,13,0,"0,48","0,96","0,00"
2,Arauca,0,0,1,0,0,0,"0,00","0,00","4,30"

Table 4: Page 14, 25 rows x 13 cols

,Agente etiológico,2025,col_2,col_3,col_4,col_5,col_6,2026,col_8,col_9,col_10,col_11,col_12
0,None,Menor de un año,1 año,2 años,3 años,4 años,Total,Menor de un año,1 año,2 años,3 años,4 años,Total
1,Bordetella pertussis,5,0,0,0,0,5,8,0,0,0,0,8
2,Rhinovirus,8,1,3,1,0,13,4,0,1,1,1,7

Table 5: Page 15, 4 rows x 5 cols

     Año Tipo de muerte Temprana Tardía Coincidente Total
0   2023                     102     56          28   186
1   2024                      82     59          26   167
2  2025p                      73     58          17   148

Table 6: Page 16, 2 rows x 3 cols

,Municipio de residencia,Promedio histórico 2022 – 2025 a SE 21,Valor observado SE 21
0,Colombia,93,56
1,Cumbal (Nariño),0,1*

In [20]:
# You can also download + parse in one step using get_weekly_bulletins
# and then download_bulletin + parse_bulletin_pdf
# Or use the PDFParser directly for fine-grained control:
from epidatasets.utils.pdf import PDFParser

parser = PDFParser(cache_dir=pdf_path.parent, cache_ttl_days=30)
tables = parser.extract_tables(pdf_path, pages=[1, 2])  # pages 1-2 only
print(f'Extracted {len(tables)} table(s) from pages 1-2')
for t in tables:
    print(f'  Page {t.page_number}: {len(t.data)} rows x {len(t.data.columns)} cols')

INFO:epidatasets.utils.pdf:Extracted 0 table(s) from 2026_Boletin_epidemiologico_semana_21.pdf

Extracted 0 table(s) from pages 1-2

## 🔍 Data Access Notes

### Current Implementation

This accessor provides:
- ✅ Complete metadata (departments, diseases, event groups)
- ✅ Structured data access methods
- ✅ Regional and temporal filtering
- ✅ Ready-to-use data structures
- ✅ PDF bulletin download and parsing via shared `PDFParser`

### Future Enhancements

For full data access, integrate with:
1. **datos.gov.co API** - Colombia's open data portal
2. **INS SIVIGILA API** - Direct access to surveillance system

### Data Availability

| Data Type | Frequency | Access Method |
|-----------|-----------|---------------|
| Weekly bulletins | Weekly | PDF download + `PDFParser` |
| Case data | Weekly | datos.gov.co API |
| Annual summaries | Yearly | INS reports |
| Geographic data | Static | Administrative divisions |

## 💾 Export Data

Save processed data for further analysis:

In [ ]:
# Create output directory
output_dir = Path('./output')
output_dir.mkdir(exist_ok=True)

# Export departments
departments.to_csv(output_dir / 'colombia_departments.csv', index=False)
print("✅ Exported: colombia_departments.csv")

# Export diseases
diseases.to_csv(output_dir / 'colombia_diseases.csv', index=False)
print("✅ Exported: colombia_diseases.csv")

# Export event groups
event_groups.to_csv(output_dir / 'colombia_event_groups.csv', index=False)
print("✅ Exported: colombia_event_groups.csv")

print(f"\n📁 All files saved to: {output_dir.absolute()}")

## 📚 References

- **INS Colombia**: https://www.ins.gov.co/
- **SIVIGILA**: https://www.sivigila.gov.co
- **Datos Abiertos Colombia**: https://www.datos.gov.co
- **Event Groups Classification**: Resolución 2113 de 2021 (Colombia)

---

**Last Updated:** March 2026  
**Data Source:** Instituto Nacional de Salud (INS) - Colombia