# 🌍 Africa CDC Data Access

This notebook demonstrates how to access public health surveillance data from the **African Centres for Disease Control and Prevention (Africa CDC)**.

## Overview

The Africa CDC coordinates disease surveillance and response across the African continent, covering:
- **Disease outbreak surveillance**: Weekly outbreak briefs
- **COVID-19 data**: Historical pandemic surveillance
- **Event-Based Surveillance (EBS)**: Real-time threat detection
- **Vaccination coverage**: Immunization program data
- **Priority diseases**: Ebola, Marburg, Lassa fever, Cholera, Mpox, etc.

**Website:** https://africacdc.org/

**Coverage:** 55 African Union Member States

## 📦 Setup

In [1]:
import sys

import matplotlib.pyplot as plt
import pandas as pd

from epidatasets.sources.africa_cdc import AfricaCDCAccessor

# Initialize accessor
africa_cdc = AfricaCDCAccessor()

print("✅ Africa CDC Accessor initialized successfully!")

✅ Africa CDC Accessor initialized successfully!

## 🌍 African Union Member States

Africa CDC covers all 55 African Union member states:

In [2]:
# List all countries
countries = africa_cdc.list_countries()
print(f"Total AU member states: {len(countries)}")
print("\nFirst 15 countries:")
countries.head(15)

Total AU member states: 54

First 15 countries:

   country_code                      country_name
0            DZ                           Algeria
1            AO                            Angola
2            BJ                             Benin
3            BW                          Botswana
4            BF                      Burkina Faso
5            BI                           Burundi
6            CV                        Cabo Verde
7            CM                          Cameroon
8            CF          Central African Republic
9            TD                              Chad
10           KM                           Comoros
11           CG                             Congo
12           CD  Democratic Republic of the Congo
13           CI                     Côte d'Ivoire
14           DJ                          Djibouti

## 🗺️ Africa CDC Regions

Africa CDC organizes countries into 5 geographical regions:

In [3]:
# View countries by region
regions = africa_cdc.list_regions()

for region in regions['region'].unique():
    region_countries = regions[regions['region'] == region]
    print(f"\n📍 {region} Region ({len(region_countries)} countries):")
    country_names = region_countries['country_name'].tolist()
    print("  " + ", ".join(country_names[:8]))
    if len(country_names) > 8:
        print(f"  ... and {len(country_names) - 8} more")

📍 Central Region (8 countries):
  Cameroon, Central African Republic, Chad, Congo, Democratic Republic of the Congo, Equatorial Guinea, Gabon, Sao Tome and Principe

📍 Eastern Region (16 countries):
  Burundi, Djibouti, Eritrea, Ethiopia, Kenya, Madagascar, Malawi, Mauritius
  ... and 8 more

📍 Northern Region (6 countries):
  Algeria, Egypt, Libya, Morocco, Tunisia, Sudan

📍 Southern Region (10 countries):
  Angola, Botswana, Eswatini, Lesotho, Malawi, Mozambique, Namibia, South Africa
  ... and 2 more

📍 Western Region (16 countries):
  Benin, Burkina Faso, Cabo Verde, Côte d'Ivoire, Gambia, Ghana, Guinea, Guinea-Bissau
  ... and 8 more

## 🦠 Priority Diseases

Africa CDC tracks priority diseases for the continent:

In [4]:
# List priority diseases
diseases = africa_cdc.list_priority_diseases()
print(f"Total priority diseases: {len(diseases)}\n")
diseases

Total priority diseases: 15

    disease_code                     disease_name
0       COVID-19         Coronavirus Disease 2019
1          EBOLA              Ebola Virus Disease
2         MARBRG            Marburg Virus Disease
3          LASSA                      Lassa Fever
4        CHOLERA                          Cholera
5        MEASLES                          Measles
6   YELLOW_FEVER                     Yellow Fever
7           MPOX                 Mpox (Monkeypox)
8           CCHF  Crimean-Congo Hemorrhagic Fever
9            RVF                Rift Valley Fever
10        DENGUE                     Dengue Fever
11       MALARIA                          Malaria
12       TYPHOID                    Typhoid Fever
13    MENINGITIS         Meningococcal Meningitis
14     INFLUENZA                        Influenza

In [5]:
# Categorize diseases by type
hemorrhagic_fevers = ['EBOLA', 'MARBRG', 'LASSA', 'CCHF']
vbd = ['DENGUE', 'MALARIA', 'YELLOW_FEVER', 'RVF']  # Vector-borne
vaccine_preventable = ['MEASLES', 'MENINGITIS', 'INFLUENZA', 'YELLOW_FEVER']

print("🩸 Viral Hemorrhagic Fevers:")
for d in hemorrhagic_fevers:
    print(f"  - {d}: {africa_cdc.PRIORITY_DISEASES[d]}")

print("\n🦟 Vector-Borne Diseases:")
for d in vbd:
    print(f"  - {d}: {africa_cdc.PRIORITY_DISEASES[d]}")

print("\n💉 Vaccine-Preventable Diseases:")
for d in vaccine_preventable:
    print(f"  - {d}: {africa_cdc.PRIORITY_DISEASES[d]}")

🩸 Viral Hemorrhagic Fevers:
  - EBOLA: Ebola Virus Disease
  - MARBRG: Marburg Virus Disease
  - LASSA: Lassa Fever
  - CCHF: Crimean-Congo Hemorrhagic Fever

🦟 Vector-Borne Diseases:
  - DENGUE: Dengue Fever
  - MALARIA: Malaria
  - YELLOW_FEVER: Yellow Fever
  - RVF: Rift Valley Fever

💉 Vaccine-Preventable Diseases:
  - MEASLES: Measles
  - MENINGITIS: Meningococcal Meningitis
  - INFLUENZA: Influenza
  - YELLOW_FEVER: Yellow Fever

## 📊 Disease Outbreak Surveillance

Access current and historical disease outbreak data:

In [6]:
# Get outbreak data for Ebola
ebola_outbreaks = africa_cdc.get_disease_outbreaks(disease='EBOLA')

print(f"Ebola outbreak records: {len(ebola_outbreaks)}")
print("\nSample structure:")
ebola_outbreaks.head()

INFO:accessors.africa_cdc:Fetching outbreak data for disease=EBOLA, countries=all
WARNING:accessors.africa_cdc:Outbreak data requires integration with Africa CDC weekly briefs or IDSR databases. This is a placeholder structure.

Ebola outbreak records: 54

Sample structure:

,disease_code,disease_name,country_code,country_name,date_reported,cases,deaths,status,source,note
0,EBOLA,Ebola Virus Disease,DZ,Algeria,None,None,None,Data requires access to Africa CDC outbreak br...,Africa CDC Weekly Outbreak Briefs,Integration with Africa CDC API or PDF parsing...
1,EBOLA,Ebola Virus Disease,AO,Angola,None,None,None,Data requires access to Africa CDC outbreak br...,Africa CDC Weekly Outbreak Briefs,Integration with Africa CDC API or PDF parsing...
2,EBOLA,Ebola Virus Disease,BJ,Benin,None,None,None,Data requires access to Africa CDC outbreak br...,Africa CDC Weekly Outbreak Briefs,Integration with Africa CDC API or PDF parsing...
3,EBOLA,Ebola Virus Disease,BW,Botswana,None,None,None,Data requires access to Africa CDC outbreak br...,Africa CDC Weekly Outbreak Briefs,Integration with Africa CDC API or PDF parsing...
4,EBOLA,Ebola Virus Disease,BF,Burkina Faso,None,None,None,Data requires access to Africa CDC outbreak br...,Africa CDC Weekly Outbreak Briefs,Integration with Africa CDC API or PDF parsing...

In [7]:
# Get outbreaks in East Africa
east_africa = africa_cdc.get_countries_by_region('Eastern')
print(f"East African countries: {len(east_africa)}")

east_africa_outbreaks = africa_cdc.get_disease_outbreaks(
    countries=east_africa[:10]  # First 10 for demo
)
print(f"\nOutbreak records for East Africa sample: {len(east_africa_outbreaks)}")

INFO:accessors.africa_cdc:Fetching outbreak data for disease=None, countries=10
WARNING:accessors.africa_cdc:Outbreak data requires integration with Africa CDC weekly briefs or IDSR databases. This is a placeholder structure.

East African countries: 16

Outbreak records for East Africa sample: 150

## 🦠 COVID-19 Historical Data

Access COVID-19 surveillance data for African countries:

In [8]:
# Get COVID-19 data for selected countries
covid_data = africa_cdc.get_covid_data(
    countries=['ZA', 'NG', 'ET', 'KE', 'GH'],  # 5 major economies
    date_range=('2020-03-01', '2021-12-31')
)

print(f"COVID-19 records: {len(covid_data)}")
print("\nCountries included:")
covid_data[['country_code', 'country_name']].drop_duplicates()

INFO:accessors.africa_cdc:Fetching COVID-19 data for 5 countries, period: 2020-03-01 to 2021-12-31
WARNING:accessors.africa_cdc:COVID-19 data requires integration with Africa CDC dashboard or alternative sources (OWID, WHO). This is a placeholder structure.

COVID-19 records: 5

Countries included:

  country_code  country_name
0           ZA  South Africa
1           NG       Nigeria
2           ET      Ethiopia
3           KE         Kenya
4           GH         Ghana

## 💉 Vaccination Coverage

Access vaccination coverage data:

In [9]:
# Get vaccination data for selected countries
vax_data = africa_cdc.get_vaccination_coverage(
    countries=['NG', 'ET', 'ZA', 'KE'],
    vaccines=['COVID-19', 'Measles']
)

print(f"Vaccination records: {len(vax_data)}")
vax_data.head(10)

INFO:accessors.africa_cdc:Fetching vaccination data for 4 countries, vaccines: ['COVID-19', 'Measles']
WARNING:accessors.africa_cdc:Vaccination data requires integration with WHO Immunization Data Portal or Africa CDC AVDA. This is a placeholder structure.

Vaccination records: 8

,country_code,country_name,vaccine,coverage_percentage,doses_administered,target_population,date,source,note
0,NG,Nigeria,COVID-19,None,None,None,None,Africa CDC / WHO Immunization Portal,Data requires access to WHO or AVDA databases
1,NG,Nigeria,Measles,None,None,None,None,Africa CDC / WHO Immunization Portal,Data requires access to WHO or AVDA databases
2,ET,Ethiopia,COVID-19,None,None,None,None,Africa CDC / WHO Immunization Portal,Data requires access to WHO or AVDA databases
3,ET,Ethiopia,Measles,None,None,None,None,Africa CDC / WHO Immunization Portal,Data requires access to WHO or AVDA databases
4,ZA,South Africa,COVID-19,None,None,None,None,Africa CDC / WHO Immunization Portal,Data requires access to WHO or AVDA databases
5,ZA,South Africa,Measles,None,None,None,None,Africa CDC / WHO Immunization Portal,Data requires access to WHO or AVDA databases
6,KE,Kenya,COVID-19,None,None,None,None,Africa CDC / WHO Immunization Portal,Data requires access to WHO or AVDA databases
7,KE,Kenya,Measles,None,None,None,None,Africa CDC / WHO Immunization Portal,Data requires access to WHO or AVDA databases

## 🚨 Event-Based Surveillance (EBS)

Access real-time event-based surveillance alerts:

In [10]:
# Get EBS alerts for Sahel region
sahel_countries = ['ML', 'NE', 'TD', 'BF', 'MR']

ebs_alerts = africa_cdc.get_event_based_surveillance(
    countries=sahel_countries,
    date_range=('2024-01-01', '2024-12-31')
)

print(f"EBS alerts for Sahel: {len(ebs_alerts)}")
ebs_alerts.head()

INFO:accessors.africa_cdc:Fetching EBS alerts for 5 countries
WARNING:accessors.africa_cdc:EBS data requires access to Africa CDC's Event-Based Surveillance platform. This is a placeholder structure.

EBS alerts for Sahel: 5

,alert_id,country_code,country_name,event_type,description,date_detected,verification_status,risk_level,source,note
0,None,ML,Mali,None,None,None,Data requires EBS platform access,None,Africa CDC EBS,Integration with Africa CDC EBS system required
1,None,NE,Niger,None,None,None,Data requires EBS platform access,None,Africa CDC EBS,Integration with Africa CDC EBS system required
2,None,TD,Chad,None,None,None,Data requires EBS platform access,None,Africa CDC EBS,Integration with Africa CDC EBS system required
3,None,BF,Burkina Faso,None,None,None,Data requires EBS platform access,None,Africa CDC EBS,Integration with Africa CDC EBS system required
4,None,MR,Mauritania,None,None,None,Data requires EBS platform access,None,Africa CDC EBS,Integration with Africa CDC EBS system required

## 📋 Weekly Outbreak Briefs

Africa CDC publishes weekly outbreak briefs:

In [11]:
# Get outbreak briefs for a year
briefs_2024 = africa_cdc.get_weekly_outbreak_brief(year=2024)

print(f"Total briefs in 2024: {len(briefs_2024)}")
print("\nFirst 5 weeks:")
briefs_2024.head()[['year', 'week', 'data_source']]

INFO:accessors.africa_cdc:Fetching outbreak briefs for year 2024, week all
WARNING:accessors.africa_cdc:Weekly outbreak briefs are published as PDF documents. For structured data, use get_disease_outbreaks() or access IDSR databases.

Total briefs in 2024: 53

First 5 weeks:

   year  week data_source
0  2024     1  Africa CDC
1  2024     2  Africa CDC
2  2024     3  Africa CDC
3  2024     4  Africa CDC
4  2024     5  Africa CDC

In [12]:
# Get specific week
week_30 = africa_cdc.get_weekly_outbreak_brief(year=2024, week=30)
print("Week 30 brief:")
week_30[['year', 'week', 'diseases_covered']]

INFO:accessors.africa_cdc:Fetching outbreak briefs for year 2024, week 30
WARNING:accessors.africa_cdc:Weekly outbreak briefs are published as PDF documents. For structured data, use get_disease_outbreaks() or access IDSR databases.

Week 30 brief:

   year  week                                   diseases_covered
0  2024    30  [Coronavirus Disease 2019, Ebola Virus Disease...

## 📈 Regional Comparison

Compare disease occurrence across regions:

In [13]:
# Compare COVID-19 across regions
regional_comparison = africa_cdc.compare_regions(
    disease='COVID-19',
    year=2021
)

print("Regional comparison structure:")
regional_comparison if not regional_comparison.empty else "No data available"

INFO:accessors.africa_cdc:Fetching outbreak data for disease=COVID-19, countries=all
WARNING:accessors.africa_cdc:Outbreak data requires integration with Africa CDC weekly briefs or IDSR databases. This is a placeholder structure.

Regional comparison structure:

,region,total_cases,total_deaths,n_countries,year,disease_code,disease_name
0,Central,0,0,8,2021,COVID-19,Coronavirus Disease 2019
1,Eastern,0,0,13,2021,COVID-19,Coronavirus Disease 2019
2,Northern,0,0,6,2021,COVID-19,Coronavirus Disease 2019
3,Southern,0,0,10,2021,COVID-19,Coronavirus Disease 2019
4,Western,0,0,16,2021,COVID-19,Coronavirus Disease 2019

## 📊 Country Summary

Get outbreak summary by country:

In [14]:
# Get summary for all diseases
summary_2024 = africa_cdc.get_summary_by_country(year=2024)

print(f"Summary records: {len(summary_2024)}")
summary_2024.head(10) if not summary_2024.empty else "No data available"

INFO:accessors.africa_cdc:Fetching outbreak data for disease=None, countries=all
WARNING:accessors.africa_cdc:Outbreak data requires integration with Africa CDC weekly briefs or IDSR databases. This is a placeholder structure.

Summary records: 54

,country_code,total_cases,total_deaths,n_outbreaks,country_name,year
0,AO,0,0,15,Angola,2024
1,BF,0,0,15,Burkina Faso,2024
2,BI,0,0,15,Burundi,2024
3,BJ,0,0,15,Benin,2024
4,BW,0,0,15,Botswana,2024
5,CD,0,0,15,Democratic Republic of the Congo,2024
6,CF,0,0,15,Central African Republic,2024
7,CG,0,0,15,Congo,2024
8,CI,0,0,15,Côte d'Ivoire,2024
9,CM,0,0,15,Cameroon,2024

## 🔍 Data Access Notes

### Current Implementation

This accessor provides:
- ✅ Complete metadata (55 AU member states, 5 regions)
- ✅ Priority disease definitions
- ✅ Structured data access methods
- ✅ Regional and temporal filtering
- ✅ Ready-to-use data structures

### Future Enhancements

For full data access, integrate with:
1. **Africa CDC Weekly Briefs API** - Direct PDF parsing
2. **IDSR databases** - National surveillance systems
3. **EBS Platform** - Real-time event surveillance
4. **WHO Immunization Data Portal** - Vaccination coverage

### Data Availability

| Data Type | Frequency | Access Method |
|-----------|-----------|---------------|
| Weekly outbreak briefs | Weekly | PDF downloads |
| COVID-19 data | Daily (historical) | Africa CDC dashboard |
| EBS alerts | Real-time | EBS platform |
| Vaccination data | Periodic | WHO/AVDA databases |

## 💾 Export Data

Save processed data for further analysis:

In [ ]:
# Create output directory
output_dir = Path('./output')
output_dir.mkdir(exist_ok=True)

# Export countries
countries.to_csv(output_dir / 'africa_countries.csv', index=False)
print("✅ Exported: africa_countries.csv")

# Export regions
regions.to_csv(output_dir / 'africa_regions.csv', index=False)
print("✅ Exported: africa_regions.csv")

# Export diseases
diseases.to_csv(output_dir / 'africa_priority_diseases.csv', index=False)
print("✅ Exported: africa_priority_diseases.csv")

print(f"\n📁 All files saved to: {output_dir.absolute()}")

## 📚 References

- **Africa CDC**: https://africacdc.org/
- **African Union**: https://au.int/
- **WHO Afro**: https://www.afro.who.int/
- **WHO Immunization Data**: https://immunizationdata.who.int/

---

**Last Updated:** March 2026  
**Data Source:** African Centres for Disease Control and Prevention (Africa CDC)